  {
    id: "p53",
    title: "P53 · Lions at Panthers, agent 7-leg",
    stake: "1u",
    price: "Same-game parlay",
    result: "Pending",
    note: "Agent card, score 60. Rain fell from 43 percent to about 11 percent. Total moved 50.5 to 51.5. Coker is out, Legette is on IR, so McMillan is the Carolina target. Hubbard is the risk leg. Goff and Young passing yards were left off on purpose.",
    legs: [
      { pick: "Over 51.5", price: "-110", result: "Total already moved up 2" },
      { pick: "Lions -3.5", price: "-108", result: "Carolina corners on IR" },
      { pick: "Amon-Ra St. Brown over 77.5 receiving yards", price: "main", result: "Line moved from 75.5" },
      { pick: "Tetairoa McMillan over 72.5 receiving yards", price: "main", result: "Coker out, Legette on IR" },
      { pick: "Jahmyr Gibbs over 96.5 rushing yards", price: "main", result: "Line moved from 94.5. Floor was 52" },
      { pick: "Chuba Hubbard over 64.5 rushing yards", price: "main", result: "Risk leg. Detroit run defense improved" },
      { pick: "Jahmyr Gibbs anytime", price: "-325", result: "Same path as the rush leg" },
    ],
  },
